MainPartSiteDGU/Api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from .views import *

urlpatterns = [
    path('list_students/', ListStudents.as_view(), name='api_list_students'),
    path('test/', test.as_view(), name='api_list_students'),
    path('student/<int:pk>', DitailStudents.as_view(), name='api_ditail_students'),
    path('login/', MyTokenObtainView.as_view(), name='api_token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='api_token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='api_token_verify'),
]

MainPartSiteDGU/MainPartSiteDGU/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('base/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('Students.urls')),
    path('', include('logic_for_student.urls')),
    path('api/', include('Api.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('drf_auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

MainPartSiteDGU/Students/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from .views import *

urlpatterns = [
    path('base_register/', BaseRegister.as_view(), name='base_register'),
    path('advanced_register/', AdvancedRegisterStudent.as_view(), name='advanced_register'),
    path('full_register/', FullRegisterStudent.as_view(), name='full_register'),
    path('login/', Login.as_view(), name='login'),
    path('reg_user/', Register.as_view(), name='register'),
    path('logout/', logout_system, name='logout'),
    path('list_students/', ListStudent.as_view(), name='list_students'),
    path('detail_student/<int:pk>/', DetailStudent.as_view(), name='detail_student'),
    path('detail_student/<int:pk>/_edit/', EditStudent.as_view(), name='edit_detail_student'),
    path('type_reg_student/', TypeRegisterStudent.as_view(), name='type_reg_student'),
    path('account/', Account.as_view(), name='account'),
    path('test/', Test.as_view(), name='test'),
]

MainPartSiteDGU/Students/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

# def directory_path(instance, filename):
#     return f'photo/%Y/%m.%d/{filename}'
from django.urls import reverse


class CustomUser(AbstractUser):
    ROLES = (
        ('T', 'Преподаватель'),
        ('S', 'Студент'),
        ('B', 'Ласточка'),
    )
    roles = models.CharField(choices=ROLES, max_length=2, blank=True,
                             default='S')
    middle_name = models.CharField(max_length=255, verbose_name='Отчество', blank=True)

    class Meta:
        db_table = 'Dj_CUser'

    def __str__(self):
        return self.get_full_name() or self.username

    def get_full_name(self):
        full_name = '%s %s %s' % (self.first_name, self.last_name, self.middle_name)
        return full_name.strip()


class ProfileStudent(models.Model):
    student = models.OneToOneField(to='CustomUser', on_delete=models.CASCADE, verbose_name='Студент')
    direction = models.ForeignKey(to='TypeDirection', verbose_name='Направление', on_delete=models.CASCADE,
                                  default=1)
    TYPE_STATUS = (
        ('1', '1-курс'),
        ('1-1', '1-курс-академ'),
        ('1-2', '1-курс-магистратура'),
        ('2', '2-курс'),
        ('2-1', '2-курс-академ'),
        ('2-2', '2-курс-магистратура'),
        ('3', '3-курс'),
        ('3-1', '3-курс-академ'),
        ('4', '4-курс'),
        ('4-1', '4-курс-академ'),
    )
    course = models.CharField(choices=TYPE_STATUS, verbose_name='курс', default='1', max_length=3)
    student_status = models.ForeignKey(to='StatusStudent', verbose_name='статус студента',
                                       on_delete=models.SET_NULL, default=1, null=True)
    photo_student = models.FileField(upload_to='photo_student/%Y/%m.%d/', verbose_name='фото студента',
                                     default='default_img/default.png', )
    photo_social_reference = models.FileField(upload_to='social_reference/', verbose_name='Социальная справка',
                                              default='default_img/default.png', )
    start_social_reference = models.DateField(verbose_name='дата назначения справки', blank=True, null=True)
    end_social_reference = models.DateField(verbose_name='дата завершения действия справки', blank=True, null=True)

    ORGANIZATION = (
        ('К', 'КДМ'),
        ('П', 'ПРОФКОМ'),
        ('С', 'СНО'),
        ('О', 'Отсутствует'),
    )
    organization = models.CharField(choices=ORGANIZATION, verbose_name='организация', max_length=1, default='О')
    organization_sector = models.ForeignKey(to='OrganizationSector', verbose_name='Сектор организации',
                                            on_delete=models.SET_NULL, null=True)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания', )
    time_update = models.DateTimeField(auto_now=True, verbose_name='дата изменения', )

    class Meta:
        db_table = 'ProfileStudent'

    def get_absolute_url(self):
        return reverse('detail_student', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.student.get_full_name()}'


class StatusStudent(models.Model):
    name = models.CharField(verbose_name='статус', max_length=255, )

    class Meta:
        db_table = 'StatusStudent'

    def __str__(self):
        return self.name


class TypeDirection(models.Model):
    name = models.CharField(verbose_name='Направление', max_length=255, )

    class Meta:
        db_table = 'TypeDirection'

    def __str__(self):
        return self.name


class OrganizationSector(models.Model):
    name = models.CharField(verbose_name='Сектор организации', max_length=255, )

    class Meta:
        db_table = 'OrganizationSector'

    def __str__(self):
        return self.name

MainPartSiteDGU/Students/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
# from ..MainPartSiteDGU.settings import AUTH_USER_MODEL
from .models import *
import re


class FormBaseRegisterStudent(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Имя', label='Имя',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=30, required=False, help_text='Фамилия', label='Фамилия',
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    middle_name = forms.CharField(max_length=30, required=False, help_text='Отчество', label='Отчество',
                                  widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = ProfileStudent
        fields = ('first_name', 'last_name', 'middle_name', 'direction', 'course', 'photo_student',)
        widgets = {
            'direction': forms.Select(attrs={'class': 'form-select'}),
            'course': forms.Select(attrs={'class': 'form-select'}),
            'photo_student': forms.FileInput(attrs={'class': 'custom-file-input'}),
        }


class FormAdvancedRegisterStudent(FormBaseRegisterStudent):
    class Meta:
        model = ProfileStudent
        # fields = '__all__'
        fields = ('first_name', 'last_name', 'middle_name', 'direction', 'course', 'student_status', 'photo_student',
                  'photo_social_reference', 'start_social_reference', 'end_social_reference')
        widgets = {
            'direction': forms.Select(attrs={'class': 'form-select'}),
            'course': forms.Select(attrs={'class': 'form-select'}),
            'student_status': forms.Select(attrs={'class': 'form-select'}),
            'photo_student': forms.FileInput(attrs={'class': 'custom-file-input'}),
            'photo_social_reference': forms.FileInput(attrs={'class': 'custom-file-input'}),
            'start_social_reference': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ГГГГ-ММ-ДД'}),
            'end_social_reference': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ГГГГ-ММ-ДД'}),

        }


class FormFullRegisterStudent(FormBaseRegisterStudent):
    class Meta:
        model = ProfileStudent
        fields = ('first_name', 'last_name', 'middle_name', 'direction', 'course', 'student_status', 'photo_student',
                  'photo_social_reference', 'start_social_reference', 'end_social_reference', 'organization',
                  'organization_sector',)
        widgets = {
            'direction': forms.Select(attrs={'class': 'form-select'}),
            'course': forms.Select(attrs={'class': 'form-select', 'readonly': 'readonly'}, ),
            'student_status': forms.Select(attrs={'class': 'form-select'}),
            'organization': forms.Select(attrs={'class': 'form-select'}),
            'organization_sector': forms.Select(attrs={'class': 'form-select'}),
            'photo_student': forms.FileInput(attrs={'class': 'custom-file-input'}),
            'photo_social_reference': forms.FileInput(attrs={'class': 'custom-file-input'}),
            'start_social_reference': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ГГГГ-ММ-ДД'}),
            'end_social_reference': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ГГГГ-ММ-ДД'}),
        }


class FormLogin_s(AuthenticationForm):
    username = UsernameField(label='Логин', widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form_input'}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form_input'}),
    )


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control form-input'}))
    password2 = forms.CharField(label='Повтор пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-input'}))

    # is_active = forms.CharField()

    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2',)

MainPartSiteDGU/Students/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic, View
import logging
from .forms import *
from ExecutableCode.new_password import new_password
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

log = logging.getLogger('my_log')

menu = [{'student': [{'title': "Главная", 'url_name': 'list_events'},
                     {'title': "Добавить Мероприятие", 'url_name': 'create_events'},
                     {'title': "Личный кабинет", 'url_name': 'account'}],
         'teacher': [{'title': "Главная", 'url_name': 'list_events'},
                     {'title': "Добавить Мероприятие", 'url_name': 'create_events'},
                     {'title': "Список студентов ", 'url_name': 'list_students'},
                     {'title': "Добавить студента", 'url_name': 'type_reg_student'}],
         'birds': [{'title': "Главная", 'url_name': 'list_events'},
                   {'title': "Добавить Мероприятие", 'url_name': 'create_events'},
                   {'title': "Список студентов ", 'url_name': 'list_students'},
                   {'title': "Личный кабинет", 'url_name': 'account'}],
         }]


class BaseRegister(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = ['Students.add_customuser', 'Students.change_customuser', 'Students.view_customuser', ]
    form_class = FormBaseRegisterStudent
    template_name = 'Students/templates/add_student.html'

    def get_success_url(self):
        return reverse(
            'type_reg_student',
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reg'] = False
        context['menu'] = menu
        return context

    def form_valid(self, form):
        group = Group.objects.get(name='Студент')
        new_user = CustomUser.objects.create_user(username=form.cleaned_data['last_name'], password=new_password(16),
                                                  first_name=form.cleaned_data['first_name'],
                                                  last_name=form.cleaned_data['last_name'],
                                                  middle_name=form.cleaned_data['middle_name'],
                                                  )
        new_user.groups.add(group)
        new_user.save()
        form.instance.student = new_user
        return super().form_valid(form)


class AdvancedRegisterStudent(BaseRegister):
    form_class = FormAdvancedRegisterStudent


class FullRegisterStudent(BaseRegister):
    form_class = FormFullRegisterStudent


class Login(LoginView):
    form_class = FormLogin_s
    template_name = 'Students/templates/login.html'

    def get_success_url(self):
        return reverse_lazy('list_events')


class Register(UserPassesTestMixin, generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'Students/templates/login.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        return reverse_lazy('list_students')


def logout_system(request):
    logout(request)
    return redirect('login')


class ListStudent(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = ['Students.view_customuser']
    template_name = 'Students/templates/list_student.html'
    paginate_by = 5
    model = ProfileStudent
    context_object_name = 'model'

    def get_context_data(self, *, object_list=None, **kwargs):
        log.info('test')
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['pagination'] = True
        return context

    def get_queryset(self):
        return ProfileStudent.objects.select_related('student', 'student_status', 'organization_sector',
                                                     'direction')


class DetailStudent(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    permission_required = ['Students.view_customuser']
    model = ProfileStudent
    template_name = 'Students/templates/detail_student.html'
    context_object_name = 'student'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['edit'] = False
        return context


class EditStudent(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = ['Students.add_customuser', 'Students.change_customuser', ]
    model = ProfileStudent
    template_name = 'Students/templates/detail_student.html'
    context_object_name = 'student'
    form_class = FormFullRegisterStudent

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['edit'] = True
        return context

    def get_success_url(self):
        return reverse(
            'detail_student',
            kwargs={'pk': self.object.pk}
        )

    def form_valid(self, form):
        first_name = self.request.POST['first_name']
        last_name = self.request.POST['last_name']
        middle_name = self.request.POST['middle_name']
        user = self.object.student
        user.first_name = first_name
        user.last_name = last_name
        user.middle_name = middle_name
        user.save()
        return super().form_valid(form)


class TypeRegisterStudent(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ['Students.add_customuser', ]

    def get(self, request):
        button = [('Базовая', 'base_register'), ('Расширенная', 'advanced_register'), ('Полная', 'full_register')]
        return render(request, 'Students/templates/add_student.html', {'but': button, 'reg': True, 'menu': menu})


class Account(LoginRequiredMixin, generic.TemplateView):
    template_name = 'Students/templates/student_account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # model = ProfileStudent.objects.select_related('student', 'student_status',
        #                                               'organization_sector',
        #                                               'direction').get(student=self.request.user)
        model = self.request.user.profilestudent
        context['menu'] = menu
        context['account'] = model
        context['form'] = FormFullRegisterStudent(instance=model)
        return context


class Test(generic.TemplateView):
    template_name = 'Students/templates/test.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test'] = 'ghbdtn'
        return context

MainPartSiteDGU/Students/templates/Students/for_base/add_student.html
{% extends 'Students/Base_student.html' %}

{% block content %}
    {% if reg %}
        <div class="container">
            <div class="w-30">
                {% for bt in but %}
                    <a href="{% url bt.1 %}" class="bt-type-reg">{{ bt.0 }}
                    </a>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="container" style="display: flex">
            <div class="col-sm-6 " style="margin-right: 150px">
                <form action="." method="post" class="needs-validation" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for f in form %}
                        <p><label class="form-check-label" for="{{ f.id_for_label }}">{{ f.label }}:</label> {{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <hr class="my-4">
                    <button class="w-100 btn btn-primary btn-lg" type="submit" href="{% url 'type_reg_student' %}">Добавить Студента</button>
                </form>
            </div>
            <img src="https://oms.karelia.ru/upload/iblock/9c8/9c862841f21b95414ad281b484ccad3e.jpg" alt="register_foto"
                 width="500" height="300" style="margin-top: 150px">
        </div>
    {% endif %}
{% endblock %}

MainPartSiteDGU/Students/templates/Students/for_base/create_events.html
{% extends 'Students/Base_student.html' %}

{% block content %}
    <div class="container">
            <div class="events">
                <form action="." method="post" class="needs-validation" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for f in form %}
                        <p><label class="form-check-label" for="{{ f.id_for_label }}">{{ f.label }}:</label> {{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <hr class="my-4">
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Добавить мероприятие</button>
                </form>
            </div>
    </div>
{% endblock %}

MainPartSiteDGU/Students/templates/Students/for_base/detail_events.html
{% extends 'Students/Base_student.html' %}

{% block content %}
    <div class="container">
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if not edit %}
                <div class="detail-event">
                    <a href="{{ ditail_event.photo.url }}">
                        <img src="{{ ditail_event.photo.url }}" alt="фото мероприятия" width="350px" height="250px"
                             class="photo-event"></a>
                </div>
                <h4><p><label class="form-label" style="margin-right: 20px">Название мероприятия:</label>
                    {{ ditail_event.name }}</p></h4>
                <h4><p><label class="form-label" style="margin-right: 20px">Описание мероприятия:</label>
                    {{ ditail_event.text }}</p></h4>
                <h4><p><label class="form-label" style="margin-right: 20px">Дата мероприятия:</label>
                    {{ ditail_event.date }}</p></h4>
                <h4><p><label class="form-label" style="margin-right: 20px">Время мероприятия:</label>
                    {{ ditail_event.time }}</p></h4>
            {% elif ditail_event.user == request.user and edit %}
                <div class="detail-event">
                    <a href="{{ ditail_event.photo.url }}">
                        <img src="{{ ditail_event.photo.url }}" alt="фото мероприятия" width="350px" height="250px"
                             class="photo-event"></a>
                </div>
                {% for f in form %}
                    <h4><p><label class="form-label" for="{{ f.id_for_label }}"
                                  style="margin-right: 20px">{{ f.label }}:</label>{{ f }}</p></h4>
                    <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
            {% endif %}
            {% if not edit %}
                <div style="display: flex; flex-direction: row; width: 700px; margin: 0 auto">
                    {% if ditail_event.user == request.user %}
                        <a class="w-100 btn btn-primary btn-lg" style="margin-left: 10px"
                           href="{% url 'edit_detail_events' pk=ditail_event.id %}">Отредактировать</a>
                    {% endif %}
                    <a class="w-100 btn btn-primary btn-lg" style="margin-left: 10px"
                       href="{% url 'list_events' %}">Назад</a>
                </div>
            {% elif ditail_event.user == request.user and edit %}
                <div style="display: flex; flex-direction: row; width: 700px; margin: 0 auto">
                    <button class="w-100 btn btn-primary btn-lg" style="margin-right: 10px" type="submit">Принять
                    </button>
                    <a class="w-100 btn btn-primary btn-lg" style="margin-left: 10px"
                       href="{% url 'detail_events' pk=ditail_event.id %}">отмена</a>
                </div>
            {% endif %}
        </form>
    </div>

{% endblock %}

MainPartSiteDGU/Students/templates/Students/for_base/detail_student.html
{% extends 'Students/Base_student.html' %}

{% block content %}
    <div class="container">
        {% if not edit %}
            <div class="detailstudent">
                <img src="{{ student.photo_student.url }}" alt="фото студента" width="350px" height="250px"
                     class="photostudent">
            </div>
            <h3 class="infostudent">ФИО: <span>{{ student.student.get_full_name }}</span></h3>
            <h3 class="infostudent">Статус студента: <span>{{ student.student_status }}</span></h3>
            <h3 class="infostudent">Курс: <span>{{ student.get_course_display }}</span></h3>
            <h3 class="infostudent">Направление: <span>{{ student.direction }}</span></h3>
            {% if student.photo_social_reference %}
                <h3 class="infostudent">Социальная справка: <a href="{{ student.photo_social_reference.url }}"
                                                               style="color: #46b4e3; text-decoration: none;">
                    Социальная справка</a></h3>
            {% else %}
                <h3 class="infostudent">Социальная справка: <span>нету</span></h3>
            {% endif %}
            <div style="display: flex; flex-direction: row; width: 700px; margin: 0 auto">
                {% if request.user.roles == 'T' and not edit %}
                    <a class="w-100 btn btn-primary btn-lg" style="margin-left: 10px"
                       href="{% url 'edit_detail_student' pk=student.id %}">Отредактировать</a>
                {% endif %}
                <a class="w-100 btn btn-primary btn-lg" style="margin-left: 10px"
                   href="{% url 'list_students' %}">Назад</a>
            </div>

        {% elif edit %}
            <form action="." method="post" enctype="multipart/form-data">
                <div class="detailstudent">
                    <img src="{{ student.photo_student.url }}" alt="фото студента" width="350px" height="250px"
                         class="photostudent">
                    <a href="{{ student.photo_social_reference.url }}"><img
                            src="{{ student.photo_social_reference.url }}" alt="фото студента"
                            width="350px" height="250px"
                            class="photostudent"></a>
                </div>
                {% csrf_token %}
                {% for f in form %}
                    {% if f.name == 'first_name' %}
                        <h6>
                            <p>
                                <label class="form-label" for="{{ f.id_for_label }}"
                                       style="margin-right: 20px">{{ f.label }}:</label>
                                <input type="text" name="first_name" class="form-control" maxlength="30"
                                       id="id_last_name" value={{ student.student.first_name }}>
                            </p>
                        </h6>
                        <div class="form-error">{{ f.errors }}</div>
                    {% elif f.name ==  'last_name' %}
                        <h6>
                            <p>
                                <label class="form-label" for="{{ f.id_for_label }}"
                                       style="margin-right: 20px">{{ f.label }}:</label>
                                <input type="text" name="last_name" class="form-control" maxlength="30"
                                       id="id_last_name" value={{ student.student.last_name }}>
                            </p>
                        </h6>
                        <div class="form-error">{{ f.errors }}</div>
                    {% elif f.name ==  'middle_name' %}
                        <h6>
                            <p>
                                <label class="form-label" for="{{ f.id_for_label }}"
                                       style="margin-right: 20px">{{ f.label }}:</label>
                                <input type="text" name="middle_name" class="form-control" maxlength="30"
                                       id="id_last_name" value={{ student.student.middle_name }}>
                            </p>
                        </h6>
                        <div class="form-error">{{ f.errors }}</div>
                    {% else %}
                        <h6><p><label class="form-label" for="{{ f.id_for_label }}"
                                      style="margin-right: 20px">{{ f.label }}:</label>{{ f }}</p></h6>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endif %}
                    {#                    <h6><p><label class="form-label" for="{{ f.id_for_label }}"#}
                    {#                                  style="margin-right: 20px">{{ f.label }}:</label>{{ f }}</p></h6>#}
                    {#                    <div class="form-error">{{ f.errors }}</div>#}
                {% endfor %}
                <div style="display: flex; flex-direction: row; width: 700px; margin: 0 auto">
                    <input type="submit" value="Изменить" class="w-100 btn btn-primary btn-lg">
                    <a class="w-100 btn btn-primary btn-lg" style="margin-left: 10px"
                       href="{% url 'detail_student' pk=student.id %}">отмена</a>
                </div>
            </form>
        {% endif %}
    </div>

{% endblock %}

MainPartSiteDGU/Students/templates/Students/for_base/login.html
{% extends 'Students/Base_student.html' %}
{% block content %}
    <body>
    <div class="vxod">
        <div class="col-sm-6 text-center" style="margin-left: 300px">
            <form action="." method="post" class="needs-validation">
            {% csrf_token %}
                {% for f in form %}
                    <p><label class="h5 text-center" for="{{ f.id_for_label }}">{{ f.label }}</label> {{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            </form>
        </div>
    </div>
    </body>
{% endblock %}

MainPartSiteDGU/Students/templates/Students/for_base/main_site.html
{% extends 'Students/Base_student.html' %}
{% block content %}
    <div class="container">
        {% if request.user.roles != "S" %}
            <form class="d-flex" role="search" method="post">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="ФИО студента" name="FIO">
                <button class="btn btn-outline-success" type="submit">Search</button>
                <a class="djdt-width-20 btn btn-primary btn-lg" style="margin-left: 10px"
                   href="{% url 'list_students' %}">Сброс</a>
            </form>
            {% for i in model %}
                <div class="d-flex bd-highlight mb-3" style="margin-left: 100px">
                    <div class="p-2 bd-highlight">
                        <img src="{{ i.photo_student.url }}" alt="фото студента" width="250px" height="150px">
                    </div>
                    <div class="p-2 bd-highlight">
                        <a href="{% url 'detail_student' i.pk %}" class="h2 style-href">{{ i.get_full_name }}</a>
                        <p class="h3">{{ i.get_course_display }}</p>
                        <p class="h3">{{ i.direction }}</p>
                    </div>
                </div>
            {% endfor %}
            <ul class="pagination" style="margin-left: 600px">
                {% for i in model.paginator.page_range %}
                    <li class="page-item">
                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}